### ISSUE TITLE
Setup Database & Resources

### ISSUE THREAD

**Issue by hashmaster3k** [hashmaster3k/rails_engine#1]
### Tasks:

- [x] Create Merchant Resource
- [x] Create Item Resource
- [x] Create Customer Resource
- [x] Create Invoice Resource
- [x] Create InvoiceItem Resource
- [x] Create Transaction Resource
- [x] Validate Necessary Attributes
- [x] Create Relationships
- [x] Create Merchant Resource

### Notes:

All tests passing and 100% coverage.
